# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"#\n\x0b\x43\x61lcRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"D\n\x0c\x43\x61lcResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x1c\n\x0bHashRequest\x12\r\n\x05input\x18\x01 \x01(\t\"/\n\x0cHashResponse\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x0e\n\x0c\x45mptyRequest\"\xaf\x01\n\rStatsResponse\x12>\n\x0b\x63\x61ll_counts\x18\x01 \x03(\x0b\x32).calculator.StatsResponse.CallCountsEntry\x12\x13\n\x0btotal_calls\x18\x02 \x01(\x05\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\x1a\x31\n\x0f\x43\x61llCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xbe\x03\n\nCalculator\x12\x38\n\x03\x41\x64\x64\x12\x17.calculator.CalcRequest\x1a\x18.calculator.CalcResponse\x12=\n\x08Subtract\x12\x17.calculator.CalcRequest\x1a\x18.calculator.CalcResponse\x12=\n\x08Multiply\x12\x17.calculator.CalcRequest\x1a\x18.calculator.CalcResponse\x12;\n\x06\x44ivide\x12\x17.calculator.CalcRequest\x1a\x18.calculator.CalcResponse\x12\x39\n\x04\x45\x63ho\x12\x17.calculator.EchoRequest\x1a\x18.calculator.EchoResponse\x12?\n\nSha256Hash\x12\x17.calculator.HashRequest\x1a\x18.calculator.HashResponse\x12?\n\x08GetStats\x12\x18.calculator.EmptyRequest\x1a\x19.calculator.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSRESPONSE_CALLCOUNTSENTRY']._loaded_options = None
  _globals['_STATSRESPONSE_CALLCOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_CALCREQUEST']._serialized_start=32
  _globals['_CALCREQUEST']._serialized_end=67
  _globals['_CALCRESPONSE']._serialized_start=69
  _globals['_CALCRESPONSE']._serialized_end=137
  _globals['_ECHOREQUEST']._serialized_start=139
  _globals['_ECHOREQUEST']._serialized_end=169
  _globals['_ECHORESPONSE']._serialized_start=171
  _globals['_ECHORESPONSE']._serialized_end=221
  _globals['_HASHREQUEST']._serialized_start=223
  _globals['_HASHREQUEST']._serialized_end=251
  _globals['_HASHRESPONSE']._serialized_start=253
  _globals['_HASHRESPONSE']._serialized_end=300
  _globals['_EMPTYREQUEST']._serialized_start=302
  _globals['_EMPTYREQUEST']._serialized_end=316
  _globals['_STATSRESPONSE']._serialized_start=319
  _globals['_STATSRESPONSE']._serialized_end=494
  _globals['_STATSRESPONSE_CALLCOUNTSENTRY']._serialized_start=445
  _globals['_STATSRESPONSE_CALLCOUNTSENTRY']._serialized_end=494
  _globals['_CALCULATOR']._serialized_start=497
  _globals['_CALCULATOR']._serialized_end=943
# @@protoc_insertion_point(module_scope)
